### ISSUE TITLE
parser library?

### ISSUE THREAD

**Issue by derhornspieler** [rndinfosecguy/Scavenger#3]
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by rndinfosecguy** [comment]
Pip should fix this issue :)

pip3 install lxml

**Comment by derhornspieler** [comment]
@rndinfosecguy Thanks dude.  Appreciate that fix.  :-)

**Comment by derhornspieler** [comment]
New error after the pip install. running P_bot_TOR.py

 [#] Waiting...
 'Doctype' object has no attribute 'has_attr'
53. iterator:
[#] Waiting...

**Comment by rndinfosecguy** [comment]
I am aware of this issue. It affects only the TOR version. Atm I try to find a new way to bypass the security captcha which is responsible for this issue.

**Comment by derhornspieler** [comment]
Added a quick work-around I think.

**Comment by rndinfosecguy** [comment]
Could you share your fix? If it works I could add it to this repository :)
