### ISSUE TITLE
Never ending Loop error

### ISSUE THREAD

**Issue by derhornspieler** [rndinfosecguy/Scavenger#5]
can't quite figure out where this error is happening on P_bot.py.  Seems to loop infinitely with the message below:

137. iterator:
Expecting value: line 1 column 1 (char 0)
138. iterator:
Expecting value: line 1 column 1 (char 0)
139. iterator:
Expecting value: line 1 column 1 (char 0)

**Comment by rndinfosecguy** [comment]
Using P_bot.py requires a pastebin PRO account and whitelisting your crawlers IP on that site.
If you do not have your IP whitelisted this column 1 error appears.
Do you have a pastebin PRO account? Then you can white list your crawlers IP here:
https://pastebin.com/api_scraping_faq

**Comment by derhornspieler** [comment]
Yes, I’ve a PRO account.  I’m going to change IP and see if this fixes the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rndinfosecguy** [comment]
That sounds good! Test it and let me know if this issue still exists afterwards :)
