### ISSUE TITLE
Problems in python on ubuntu 20.04 solution

### ISSUE THREAD

**Issue by bl00droot** [rndinfosecguy/Scavenger#6]
https://github.com/rndinfosecguy/Scavenger/blob/12fc5532c097f0709f5d74d200e8fb54bf8e6196/pbincomArchiveScrape.py#L18

add this `'html.parser' `  in line to solve the error in python3 on bs4 like this:

![image](https://user-images.githubusercontent.com/14825106/114795842-ef7aeb00-9d65-11eb-8840-45a364aa3874.png)

![image](https://user-images.githubusercontent.com/14825106/114795818-df630b80-9d65-11eb-8322-c6e05926be8f.png)

**Comment by rndinfosecguy** [comment]
Thanks for the bug report! Missed that, but fixed it now :)
